### ISSUE TITLE
Getting started receiving data

### ISSUE THREAD

**Issue by hamen** [alexbain/lirc_node#10]
Hi, I trying to create a IR remote with my RaspberryPi, but I'm having some issues getting started with `lirc_node`. I have created this simple example that is supposed to print out the keys I press on the remote:

``` js
// Receiving commands
lirc_node = require('lirc_node');
lirc_node.init();

console.log("Starting");

// Listening for commands
var listenerId = lirc_node.addListener(function(data) {
  console.log("Received IR keypress '" + data.key + "'' from remote '" + data.remote +"'");
});

console.log("Waiting for commands");
```

Unfortunately, I only get:

``` bash
pi@raspberrypi:~/$ node app.js
Starting
Waiting for commands
pi@raspberrypi:~/$
```

I get data from the remote if I use `lirc` on the shell:

```
pi@raspberrypi:~/ $ mode2 -d /dev/lirc0
space 1791693
pulse 8311
space 4302
pulse 564
space 474
pulse 537
space 510
pulse 536
[...]
```

What am I missing? Any help, please?

**Comment by gildebrand** [comment]
I'm having this issue as well. Were you able to resolve it?

**Comment by mnutt** [comment]
`lirc_node` uses the`irw` command under the hood to read commands, and `irw` connects to the `lircd` daemon. First, I would make sure `lircd` is running with `ps ax |grep lirc` and look for `/usr/sbin/lircd`. If that's running, I'd try running `irw` directly to see if that works. It should output similar output to your app:

```
$ irw
0000000040be30cf 00 KEY_VOLUMEUP appletv
0000000040be30cf 01 KEY_VOLUMEUP appletv
0000000040be9867 00 KEY_VOLUMEDOWN appletv
0000000040be9867 01 KEY_VOLUMEDOWN appletv
```

If `lircd` is running but `irw` outputs nothing, it may be that your remote is not configured / is misconfigured. I'd maybe try re-recording your remote with `irrecord`.
