### ISSUE TITLE
IR input

### ISSUE THREAD

**Issue by markstickley** [alexbain/lirc_node#3]
Not an issue, more of a question: I'm developing a node app that will accept IR input and was looking for a library to help me out. I haven't found one so I will write one myself, but would you be interested in integrating support for input as well as output into lirc_node? If so I can work on it as part of this project and submit a pull request when I'm done...

Thanks!

**Comment by alexbain** [comment]
Hi Mark - a bit late to respond, but yes that would be great to add to this project.

**Comment by alexbain** [comment]
Implemented and merged, thanks.
