### ISSUE TITLE
Update npm version

### ISSUE THREAD

**Issue by tester22** [alexbain/lirc_node#5]
Please update the version number an make an push to npm.

**Comment by RichardSlater** [comment]
Seconded, I'm using the `irrecieve` to great effect using a old remote control to turn Philips Hue lights on and off.  Keep up the good work :)

**Comment by randallagordon** [comment]
@RichardSlater That's a great idea, I may have to follow your lead with my Hues! :D

**Comment by alexbain** [comment]
Version 0.0.2 has been released. Thanks guys, enjoy!
